name: tech_tools
description: "Tech Tools for Booksystems Tech Support"
publish_to: 'none'
version: 2.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.9.2
  provider: ^6.1.2
  http: ^1.2.2
  html: ^0.15.5
  cron: ^0.6.1
  xml: ^6.5.0
  hotkey_manager: ^0.2.3
  shared_preferences: ^2.3.4
  updat: ^1.3.2
  window_manager: ^0.3.9
  flutter_acrylic: ^1.1.4
  flutter_launcher_icons: ^0.14.3
  rename: ^3.0.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
